environment_setting: "ToyExample-v2"
exp_name: "importance_heuristic"
norm_constant: 1_000_000

episodes_optimize: 1
episodes_eval: 10
episodes_print: 1

heuristic_category: "importance_heuristic"
heuristic_class: "ImportanceHeuristic"

prioritized_components: [46]
prioritized_rules_range:
  replacement_threshold:
    min: 5
    max: 6
    interval: 1
  major_repair_threshold:
    min: 2
    max: 6
    interval: 1
  minor_repair_threshold:
    min: 1
    max: 6
    interval: 1
  inspection_interval:
    min: 1
    max: 10
    interval: 1

unprioritized_rules_range:
  replacement_threshold:
    min: 5
    max: 6
    interval: 1
  major_repair_threshold:
    min: 5
    max: 6
    interval: 1
  minor_repair_threshold:
    min: 2
    max: 4
    interval: 1
  inspection_interval:
    min: 1
    max: 51
    interval: 5